services:
  owncloud:
    image: 'owncloud/server:latest'
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - SERVICE_URL_OWNCLOUD_8080
      - OWNCLOUD_DOMAIN=owncloud.yourdomain.com
      - OWNCLOUD_TRUSTED_DOMAINS=owncloud.yourdomain.com
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_HOST=mariadb
      - 'OWNCLOUD_DB_NAME=${DB_NAME:-owncloud}'
      - OWNCLOUD_DB_USERNAME=USER_MARIADB
      - OWNCLOUD_DB_PASSWORD=PASSWORD_MARIADB
      - OWNCLOUD_ADMIN_USERNAME=username
      - OWNCLOUD_ADMIN_PASSWORD=your-password
      - 'OWNCLOUD_MYSQL_UTF8MB4=${MYSQL_UTF8MB4:-true}'
      - 'OWNCLOUD_REDIS_ENABLED=${REDIS_ENABLED:-true}'
      - OWNCLOUD_REDIS_HOST=redis
    healthcheck:
      test:
        - CMD
        - /usr/bin/healthcheck
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      -
        type: bind
        source: ./owncloud-data
        target: /mnt/data
  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${SERVICE_PASSWORD_MARIADBROOT}'
      - 'MYSQL_USER=${SERVICE_USER_MARIADB}'
      - 'MYSQL_PASSWORD=${SERVICE_PASSWORD_MARIADB}'
      - 'MYSQL_DATABASE=${DB_NAME:-owncloud}'
      - TZ=auto
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_bin'
      - '--max-allowed-packet=128M'
      - '--innodb-log-file-size=64M'
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - '--connect'
        - '--innodb_initialized'
      interval: 5s
      timeout: 20s
      retries: 10
    volumes:
      -
        type: bind
        source: ./owncloud-mysql-data
        target: /var/lib/mysql
  redis:
    image: 'redis:6'
    command:
      - '--databases'
      - '1'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 5s
      retries: 5
